sudo: false
os: linux
language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
env:
  matrix:
    - TEST_SUITE=unit
matrix:
  include:
    - os: linux
      node_js: "6"
      env: TEST_SUITE=coverage
    - os: linux
      node_js: "6"
      env: TEST_SUITE=standard
script: npm run $TEST_SUITE
